# Generated by Django 4.0.6 on 2022-07-13 04:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 7, 13, 4, 42, 45, 405232, tzinfo=utc))),
                ('img_url', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=250)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=250)),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
